name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Python Version
        run: python3 --version

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stop Existing Flask Process
        run: |
          pkill -f "python.*app.py" || true

      - name: Start Flask Application
        run: |
          echo "Restart Flask service..."
          sudo systemctl daemon-reload
          sudo systemctl restart flask
          
      - name: Checking Service Status
        run: |
          echo "Checking Service Status"
          sudo systemctl status flask --no-pager

      - name: Verify Deployment
        run: |
          pgrep -f "python.*app.py"
