name: Deploy Flask Application to Azure VM

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ####################################################
      # Checkout Repository
      ####################################################
      - name: Checkout Repository
        uses: actions/checkout@v4

      ####################################################
      # Configure SSH
      ####################################################
      - name: Configure SSH
        run: |
          rmdir -R ~/.ssh
          ls -lrt ~/.ssh
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY_AZURE }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh

          ssh-keyscan -H ${{ vars.VM_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          wc -l ~/.ssh/id_rsa
      - name: Verify SSH Key
        run: |
          ssh-keygen -y -f ~/.ssh/id_rsa
      ####################################################
      # Deploy
      ####################################################
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=yes \
          ${{ vars.VM_USER }}@${{ vars.VM_HOST }} << 'EOF'

            set -e

            cd /home/jm2594/app/Python-Azure-Actions

            echo "Pull latest source..."
            git pull origin main

            echo "Create virtual environment if required..."
            if [ ! -d "venv" ]; then
                python3 -m venv venv
            fi

            source venv/bin/activate

            echo "Install dependencies..."
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt

            echo "Restart Flask service..."
            sudo systemctl daemon-reload
            sudo systemctl restart flask

            echo "Service Status"
            sudo systemctl status flask --no-pager

          EOF

      ####################################################
      # Verify Deployment
      ####################################################
      - name: Verify Deployment
        run: |
          echo "Waiting for application..."

          for i in {1..10}; do
              if curl --silent --fail http://${{ vars.VM_HOST }}/health; then
                  echo ""
                  echo "Deployment Successful"
                  exit 0
              fi

              echo "Retrying in 5 seconds..."
              sleep 5
          done

          echo "Health check failed."

          exit 1
